#ifndef _TYPES_H
#define _TYPES_H

//--------------------------------------------------------------------------------------------------------------
// UccncField
//--------------------------------------------------------------------------------------------------------------

enum class UccncField : int {
  Xaxissteppin                      = 1,
  Xaxisdirpin                       = 2,
  Xaxislimitminuspin                = 3,
  Xaxislimitpluspin                 = 4,
  Xaxishomepin                      = 5,
  Xaxishomingspeed                  = 6,
  Xaxishomeoffset                   = 7,
  Xaxisstepsper                     = 8,
  Xaxisvelocity                     = 9,
  Xaxisacceleration                 = 10,
  Xaxissoftlimitminus               = 11,
  Xaxissoftlimitplus                = 12,
  Xaxiscompaccel                    = 13,
  Xaxisbacklash                     = 14,
  // R* (Reserved)
  Yaxissteppin                      = 16,
  Yaxisdirpin                       = 17,
  Yaxislimitminuspin                = 18,
  Yaxislimitpluspin                 = 19,
  Yaxishomepin                      = 20,
  Yaxishomingspeed                  = 21,
  Yaxishomeoffset                   = 22,
  Yaxisstepsper                     = 23,
  Yaxisvelocity                     = 24,
  Yaxisacceleration                 = 25,
  Yaxissoftlimitminus               = 26,
  Yaxissoftlimitplus                = 27,
  Yaxiscompaccel                    = 28,
  Yaxisbacklash                     = 29,
  // R* (Reserved)
  Zaxissteppin                      = 31,
  Zaxisdirpin                       = 32,
  Zaxislimitminuspin                = 33,
  Zaxislimitpluspin                 = 34,
  Zaxishomepin                      = 35,
  Zaxishomingspeed                  = 36,
  Zaxishomeoffset                   = 37,
  Zaxisstepsper                     = 38,
  Zaxisvelocity                     = 39,
  Zaxisacceleration                 = 40,
  Zaxissoftlimitminus               = 41,
  Zaxissoftlimitplus                = 42,
  Zaxiscompaccel                    = 43,
  Zaxisbacklash                     = 44,
  // R* (Reserved)
  Aaxissteppin                      = 46,
  Aaxisdirpin                       = 47,
  Aaxislimitminuspin                = 48,
  Aaxislimitpluspin                 = 49,
  Aaxishomepin                      = 50,
  Aaxishomingspeed                  = 51,
  Aaxishomeoffset                   = 52,
  Aaxisstepsper                     = 53,
  Aaxisvelocity                     = 54,
  Aaxisacceleration                 = 55,
  Aaxissoftlimitminus               = 56,
  Aaxissoftlimitplus                = 57,
  Aaxiscompaccel                    = 58,
  Aaxisbacklash                     = 59,
  // R* (Reserved)
  Baxissteppin                      = 61,
  Baxisdirpin                       = 62,
  Baxislimitminuspin                = 63,
  Baxislimitpluspin                 = 64,
  Baxishomepin                      = 65,
  Baxishomingspeed                  = 66,
  Baxishomeoffset                   = 67,
  Baxisstepsper                     = 68,
  Baxisvelocity                     = 69,
  Baxisacceleration                 = 70,
  Baxissoftlimitminus               = 71,
  Baxissoftlimitplus                = 72,
  Baxiscompaccel                    = 73,
  Baxisbacklash                     = 74,
  // R* (Reserved)
  Caxissteppin                      = 76,
  Caxisdirpin                       = 77,
  Caxislimitminuspin                = 78,
  Caxislimitpluspin                 = 79,
  Caxishomepin                      = 80,
  Caxishomingspeed                  = 81,
  Caxishomeoffset                   = 82,
  Caxisstepsper                     = 83,
  Caxisvelocity                     = 84,
  Caxisacceleration                 = 85,
  Caxissoftlimitminus               = 86,
  Caxissoftlimitplus                = 87,
  Caxiscompaccel                    = 88,
  Caxisbacklash                     = 89,
  // R* (Reserved)
  Estoppin                          = 91,
  Probepin1                         = 92,
  Indexpin                          = 93,
  Indexprescaler                    = 94,
  Chargepumppin                     = 95,
  Currenthilowpin                   = 96,
  G54_CurrentcoordX                 = 97,
  G54_CurrentcoordY                 = 98,
  G54_CurrentcoordZ                 = 99,
  G54_CurrentcoordA                 = 100,
  G54_CurrentcoordB                 = 101,
  G54_CurrentcoordC                 = 102,
  G55_CurrentcoordX                 = 103,
  G55_CurrentcoordY                 = 104,
  G55_CurrentcoordZ                 = 105,
  G55_CurrentcoordA                 = 106,
  G55_CurrentcoordB                 = 107,
  G55_CurrentcoordC                 = 108,
  G56_CurrentcoordX                 = 109,
  G56_CurrentcoordY                 = 110,
  G56_CurrentcoordZ                 = 111,
  G56_CurrentcoordA                 = 112,
  G56_CurrentcoordB                 = 113,
  G56_CurrentcoordC                 = 114,
  G57_CurrentcoordX                 = 115,
  G57_CurrentcoordY                 = 116,
  G57_CurrentcoordZ                 = 117,
  G57_CurrentcoordA                 = 118,
  G57_CurrentcoordB                 = 119,
  G57_CurrentcoordC                 = 120,
  G58_CurrentcoordX                 = 121,
  G58_CurrentcoordY                 = 122,
  G58_CurrentcoordZ                 = 123,
  G58_CurrentcoordA                 = 124,
  G58_CurrentcoordB                 = 125,
  G58_CurrentcoordC                 = 126,
  G59_CurrentcoordX                 = 127,
  G59_CurrentcoordY                 = 128,
  G59_CurrentcoordZ                 = 129,
  G59_CurrentcoordA                 = 130,
  G59_CurrentcoordB                 = 131,
  G59_CurrentcoordC                 = 132,
  G54_WorkoffsetX                   = 133,
  G54_WorkoffsetY                   = 134,
  G54_WorkoffsetZ                   = 135,
  G54_WorkoffsetA                   = 136,
  G54_WorkoffsetB                   = 137,
  G54_WorkoffsetC                   = 138,
  G55_WorkoffsetX                   = 139,
  G55_WorkoffsetY                   = 140,
  G55_WorkoffsetZ                   = 141,
  G55_WorkoffsetA                   = 142,
  G55_WorkoffsetB                   = 143,
  G55_WorkoffsetC                   = 144,
  G56_WorkoffsetX                   = 145,
  G56_WorkoffsetY                   = 146,
  G56_WorkoffsetZ                   = 147,
  G56_WorkoffsetA                   = 148,
  G56_WorkoffsetB                   = 149,
  G56_WorkoffsetC                   = 150,
  G57_WorkoffsetX                   = 151,
  G57_WorkoffsetY                   = 152,
  G57_WorkoffsetZ                   = 153,
  G57_WorkoffsetA                   = 154,
  G57_WorkoffsetB                   = 155,
  G57_WorkoffsetC                   = 156,
  G58_WorkoffsetX                   = 157,
  G58_WorkoffsetY                   = 158,
  G58_WorkoffsetZ                   = 159,
  G58_WorkoffsetA                   = 160,
  G58_WorkoffsetB                   = 161,
  G58_WorkoffsetC                   = 162,
  G59_WorkoffsetX                   = 163,
  G59_WorkoffsetY                   = 164,
  G59_WorkoffsetZ                   = 165,
  G59_WorkoffsetA                   = 166,
  G59_WorkoffsetB                   = 167,
  G59_WorkoffsetC                   = 168,
  TooloffsetZ                       = 169,
  PWMspindle_PWMpin                 = 170,
  PWMspindle_dirpin                 = 171,
  PWMspindle_PWMfreque              = 172,
  Stepdirspindle_Stepp              = 173,
  Stepdirspindle_Dirpi              = 174,
  Stepdirspindle_Stepsperrotation   = 175,
  Stepdirspindle_Acceleration       = 176,
  Spindle_Minvelocity               = 177,
  Spindle_Maxvelocity               = 178,
  Spindle_M3relaypin                = 179,
  Spindle_M4relaypin                = 180,
  Spindle_M3delayon                 = 181,
  Spindle_M3delayoff                = 182,
  Spindle_M4delayon                 = 183,
  Spindle_M4delayoff                = 184,
  Spindle_M7relaypin                = 185,
  Spindle_M8relaypin                = 186,
  Spindle_M7delayon                 = 187,
  Spindle_M8delayon                 = 188,
  Spindle_M9delay                   = 189,
  Comm_buffer_size                  = 190,
  CV_stopangledegrees               = 191,
  CV_Lookaheadlines                 = 192,
  CV_Linearerrormax                 = 193,
  CV_Cornererrormax                 = 194,
  PositionDROsdigits                = 195,
  ToolZoffset1                      = 196,
  ToolZoffset2                      = 197,
  ToolZoffset3                      = 198,
  ToolZoffset4                      = 199,
  ToolZoffset5                      = 200,
  ToolZoffset6                      = 201,
  ToolZoffset7                      = 202,
  ToolZoffset8                      = 203,
  ToolZoffset9                      = 204,
  ToolZoffset10                     = 205,
  ToolZoffset11                     = 206,
  ToolZoffset12                     = 207,
  ToolZoffset13                     = 208,
  ToolZoffset14                     = 209,
  ToolZoffset15                     = 210,
  ToolZoffset16                     = 211,
  ToolZoffset17                     = 212,
  ToolZoffset18                     = 213,
  ToolZoffset19                     = 214,
  ToolZoffset20                     = 215,
  Newprofilename                    = 216,
  CV_Linearadditionlenght           = 217,
  CV_Linearunifylength              = 218,
  THC_onpin                         = 219,
  THC_uppin                         = 220,
  THC_downpin                       = 221,
  THC_min_height                    = 222,
  THC_max_height                    = 223,
  THC_feedrate                      = 224,
  SafeZheight                       = 225,
  XposDRO                           = 226,
  YposDRO                           = 227,
  ZposDRO                           = 228,
  AposDRO                           = 229,
  BposDRO                           = 230,
  CposDRO                           = 231,
  FRODRO                            = 232,
  SRODRO                            = 233,
  THC_ondelay                       = 234,
  G73backoff                        = 235,
  // 236 - 240 R* (Reserved)
  Xaxisstepport                     = 241,
  Xaxisdirport                      = 242,
  Xaxislimitminusport               = 243,
  Xaxislimitplusport                = 244,
  Xaxishomeport                     = 245,
  Yaxisstepport                     = 246,
  Yaxisdirport                      = 247,
  Yaxislimitminusport               = 248,
  Yaxislimitplusport                = 249,
  Yaxishomeport                     = 250,
  Zaxisstepport                     = 251,
  Zaxisdirport                      = 252,
  Zaxislimitminusport               = 253,
  Zaxislimitplusport                = 254,
  Zaxishomeport                     = 255,
  Aaxisstepport                     = 256,
  Aaxisdirport                      = 257,
  Aaxislimitminusport               = 258,
  Aaxislimitplusport                = 259,
  Aaxishomeport                     = 260,
  Baxisstepport                     = 261,
  Baxisdirport                      = 262,
  Baxislimitminusport               = 263,
  Baxislimitplusport                = 264,
  Baxishomeport                     = 265,
  Caxisstepport                     = 266,
  Caxisdirport                      = 267,
  Caxislimitminusport               = 268,
  Caxislimitplusport                = 269,
  Caxishomeport                     = 270,
  Estopport                         = 271,
  Probeport1                        = 272,
  Indexport                         = 273,
  Chargepumpport                    = 274,
  Currenthilowport                  = 275,
  THC_onport                        = 276,
  THC_upport                        = 277,
  THC_downport                      = 278,
  PWMspindle_PWMport                = 279,
  PWMspindle_dirport                = 280,
  Stepdirspindle_Stepport           = 281,
  Stepdirspindle_Dirport            = 282,
  Spindle_M3relayport               = 283,
  Spindle_M4relayport               = 284,
  Spindle_M7relayport               = 285,
  Spindle_M8relayport               = 286,
  MPGpinA                           = 287,
  MPGportA                          = 288,
  MPGpinB                           = 289,
  MPGportB                          = 290,
  Inputtrigger1pin                  = 291,
  Inputtrigger1port                 = 292,
  Inputtrigger1function             = 293,
  Inputtrigger2pin                  = 294,
  Inputtrigger2port                 = 295,
  Inputtrigger2function             = 296,
  Inputtrigger3pin                  = 297,
  Inputtrigger3port                 = 298,
  Inputtrigger3function             = 299,
  Inputtrigger4pin                  = 300,
  Inputtrigger4port                 = 301,
  Inputtrigger4function             = 302,
  Inputtrigger5pin                  = 303,
  Inputtrigger5port                 = 304,
  Inputtrigger5function             = 305,
  Inputtrigger6pin                  = 306,
  Inputtrigger6port                 = 307,
  Inputtrigger6function             = 308,
  Inputtrigger7pin                  = 309,
  Inputtrigger7port                 = 310,
  Inputtrigger7function             = 311,
  Inputtrigger8pin                  = 312,
  Inputtrigger8port                 = 313,
  Inputtrigger8function             = 314,
  Inputtrigger9pin                  = 315,
  Inputtrigger9port                 = 316,
  Inputtrigger9function             = 317,
  Inputtrigger10pin                 = 318,
  Inputtrigger10port                = 319,
  Inputtrigger10function            = 320,
  Inputtrigger11pin                 = 321,
  Inputtrigger11port                = 322,
  Inputtrigger11function            = 323,
  Inputtrigger12pin                 = 324,
  Inputtrigger12port                = 325,
  Inputtrigger12function            = 326,
  Inputtrigger13pin                 = 327,
  Inputtrigger13port                = 328,
  Inputtrigger13function            = 329,
  Inputtrigger14pin                 = 330,
  Inputtrigger14port                = 331,
  Inputtrigger14function            = 332,
  Inputtrigger15pin                 = 333,
  Inputtrigger15port                = 334,
  Inputtrigger15function            = 335,
  Inputtrigger16pin                 = 336,
  Inputtrigger16port                = 337,
  Inputtrigger16function            = 338,
  Inputtrigger17pin                 = 339,
  Inputtrigger17port                = 340,
  Inputtrigger17function            = 341,
  Inputtrigger18pin                 = 342,
  Inputtrigger18port                = 343,
  Inputtrigger18function            = 344,
  Inputtrigger19pin                 = 345,
  Inputtrigger19port                = 346,
  Inputtrigger19function            = 347,
  Inputtrigger20pin                 = 348,
  Inputtrigger20port                = 349,
  Inputtrigger20function            = 350,
  Inputtrigger21pin                 = 351,
  Inputtrigger21port                = 352,
  Inputtrigger21function            = 353,
  Inputtrigger22pin                 = 354,
  Inputtrigger22port                = 355,
  Inputtrigger22function            = 356,
  Inputtrigger23pin                 = 357,
  Inputtrigger23port                = 358,
  Inputtrigger23function            = 359,
  Inputtrigger24pin                 = 360,
  Inputtrigger24port                = 361,
  Inputtrigger24function            = 362,
  Inputtrigger25pin                 = 363,
  Inputtrigger25port                = 364,
  Inputtrigger25function            = 365,
  Inputtrigger26pin                 = 366,
  Inputtrigger26port                = 367,
  Inputtrigger26function            = 368,
  Inputtrigger27pin                 = 369,
  Inputtrigger27port                = 370,
  Inputtrigger27function            = 371,
  Inputtrigger28pin                 = 372,
  Inputtrigger28port                = 373,
  Inputtrigger28function            = 374,
  Inputtrigger29pin                 = 375,
  Inputtrigger29port                = 376,
  Inputtrigger29function            = 377,
  Inputtrigger30pin                 = 378,
  Inputtrigger30port                = 379,
  Inputtrigger30function            = 380,
  Inputtrigger31pin                 = 381,
  Inputtrigger31port                = 382,
  Inputtrigger31function            = 383,
  Inputtrigger32pin                 = 384,
  Inputtrigger32port                = 385,
  Inputtrigger32function            = 386,
  Inputtrigger33pin                 = 387,
  Inputtrigger33port                = 388,
  Inputtrigger33function            = 389,
  Inputtrigger34pin                 = 390,
  Inputtrigger34port                = 391,
  Inputtrigger34function            = 392,
  Inputtrigger35pin                 = 393,
  Inputtrigger35port                = 394,
  Inputtrigger35function            = 395,
  Inputtrigger36pin                 = 396,
  Inputtrigger36port                = 397,
  Inputtrigger36function            = 398,
  Inputtrigger37pin                 = 399,
  Inputtrigger37port                = 400,
  Inputtrigger37function            = 401,
  Inputtrigger38pin                 = 402,
  Inputtrigger38port                = 403,
  Inputtrigger38function            = 404,
  Inputtrigger39pin                 = 405,
  Inputtrigger39port                = 406,
  Inputtrigger39function            = 407,
  Inputtrigger40pin                 = 408,
  Inputtrigger40port                = 409,
  Inputtrigger40function            = 410,
  Inputtrigger41pin                 = 411,
  Inputtrigger41port                = 412,
  Inputtrigger41function            = 413,
  Inputtrigger42pin                 = 414,
  Inputtrigger42port                = 415,
  Inputtrigger42function            = 416,
  Inputtrigger43pin                 = 417,
  Inputtrigger43port                = 418,
  Inputtrigger43function            = 419,
  Inputtrigger44pin                 = 420,
  Inputtrigger44port                = 421,
  Inputtrigger44function            = 422,
  Inputtrigger45pin                 = 423,
  Inputtrigger45port                = 424,
  Inputtrigger45function            = 425,
  Inputtrigger46pin                 = 426,
  Inputtrigger46port                = 427,
  Inputtrigger46function            = 428,
  Inputtrigger47pin                 = 429,
  Inputtrigger47port                = 430,
  Inputtrigger47function            = 431,
  Inputtrigger48pin                 = 432,
  Inputtrigger48port                = 433,
  Inputtrigger48function            = 434,
  // 435 - 442 R* (Reserved)
  MPGprescaler                      = 443,
  Analoginput1var                   = 444,
  Analoginput2var                   = 445,
  // R* (Reserved)
  FROanalogchannelnumber            = 447,
  FROanalogminpercent               = 448,
  FROanalogmaxpercent               = 449,
  SROanalogchannelnumber            = 450,
  SROanalogminpercent               = 451,
  SROanalogmaxpercent               = 452,
  JROanalogchannelnumber            = 453,
  JROanalogminpercent               = 454,
  JROanalogmaxpercent               = 455,
  MPGfilterconstant                 = 456,
  MPGspeedmultiplier                = 457,
  PWMspindle_PWMmindutycycle        = 458,
  PWMspindle_PWMmaxdutycycle        = 459,
  Analogoutput1var                  = 460,
  Analogoutput2var                  = 461,
  SpindlePWM_analogoutputchannel    = 462,
  Xaxisenablepin                    = 463,
  Xaxisenableport                   = 464,
  Yaxisenablepin                    = 465,
  Yaxisenableport                   = 466,
  Zaxisenablepin                    = 467,
  Zaxisenableport                   = 468,
  Aaxisenablepin                    = 469,
  Aaxisenableport                   = 470,
  Baxisenablepin                    = 471,
  Baxisenableport                   = 472,
  Caxisenablepin                    = 473,
  Caxisenableport                   = 474,
  // R* (Reserved)
  G92_offsetX                       = 500,
  G92_offsetY                       = 501,
  G92_offsetZ                       = 502,
  G92_offsetA                       = 503,
  G92_offsetB                       = 504,
  G92_offsetC                       = 505,
  Hotkey_keycode1                   = 506,
  Hotkey_function1                  = 507,
  Hotkey_keycode2                   = 508,
  Hotkey_function2                  = 509,
  Hotkey_keycode3                   = 510,
  Hotkey_function3                  = 511,
  Hotkey_keycode4                   = 512,
  Hotkey_function4                  = 513,
  Hotkey_keycode5                   = 514,
  Hotkey_function5                  = 515,
  Hotkey_keycode6                   = 516,
  Hotkey_function6                  = 517,
  Hotkey_keycode7                   = 518,
  Hotkey_function7                  = 519,
  Hotkey_keycode8                   = 520,
  Hotkey_function8                  = 521,
  Hotkey_keycode9                   = 522,
  Hotkey_function9                  = 523,
  Hotkey_keycode10                  = 524,
  Hotkey_function10                 = 525,
  Hotkey_keycode11                  = 526,
  Hotkey_function11                 = 527,
  Hotkey_keycode12                  = 528,
  Hotkey_function12                 = 529,
  Hotkey_keycode13                  = 530,
  Hotkey_function13                 = 531,
  Hotkey_keycode14                  = 532,
  Hotkey_function14                 = 533,
  Hotkey_keycode15                  = 534,
  Hotkey_function15                 = 535,
  Hotkey_keycode16                  = 536,
  Hotkey_function16                 = 537,
  Hotkey_keycode17                  = 538,
  Hotkey_function17                 = 539,
  Hotkey_keycode18                  = 540,
  Hotkey_function18                 = 541,
  Hotkey_keycode19                  = 542,
  Hotkey_function19                 = 543,
  Hotkey_keycode20                  = 544,
  Hotkey_function20                 = 545,
  Hotkey_keycode21                  = 546,
  Hotkey_function21                 = 547,
  Hotkey_keycode22                  = 548,
  Hotkey_function22                 = 549,
  Hotkey_keycode23                  = 550,
  Hotkey_function23                 = 551,
  Hotkey_keycode24                  = 552,
  Hotkey_function24                 = 553,
  Hotkey_keycode25                  = 554,
  Hotkey_function25                 = 555,
  Hotkey_keycode26                  = 556,
  Hotkey_function26                 = 557,
  Hotkey_keycode27                  = 558,
  Hotkey_function27                 = 559,
  Hotkey_keycode28                  = 560,
  Hotkey_function28                 = 561,
  Hotkey_keycode29                  = 562,
  Hotkey_function29                 = 563,
  Hotkey_keycode30                  = 564,
  Hotkey_function30                 = 565,
  Hotkey_keycode31                  = 566,
  Hotkey_function31                 = 567,
  Hotkey_keycode32                  = 568,
  Hotkey_function32                 = 569,
  Hotkey_keycode33                  = 570,
  Hotkey_function33                 = 571,
  Hotkey_keycode34                  = 572,
  Hotkey_function34                 = 573,
  Hotkey_keycode35                  = 574,
  Hotkey_function35                 = 575,
  Hotkey_keycode36                  = 576,
  Hotkey_function36                 = 577,
  Hotkey_keycode37                  = 578,
  Hotkey_function37                 = 579,
  Hotkey_keycode38                  = 580,
  Hotkey_function38                 = 581,
  Hotkey_keycode39                  = 582,
  Hotkey_function39                 = 583,
  Hotkey_keycode40                  = 584,
  Hotkey_function40                 = 585,
  Hotkey_keycode41                  = 586,
  Hotkey_function41                 = 587,
  Hotkey_keycode42                  = 588,
  Hotkey_function42                 = 589,
  Hotkey_keycode43                  = 590,
  Hotkey_function43                 = 591,
  Hotkey_keycode44                  = 592,
  Hotkey_function44                 = 593,
  Hotkey_keycode45                  = 594,
  Hotkey_function45                 = 595,
  Hotkey_keycode46                  = 596,
  Hotkey_function46                 = 597,
  Hotkey_keycode47                  = 598,
  Hotkey_function47                 = 599,
  Hotkey_keycode48                  = 600,
  Hotkey_function48                 = 601,
  Hotkey_keycode49                  = 602,
  Hotkey_function49                 = 603,
  Hotkey_keycode50                  = 604,
  Hotkey_function50                 = 605,
  Hotkey_keycode51                  = 606,
  Hotkey_function51                 = 607,
  Hotkey_keycode52                  = 608,
  Hotkey_function52                 = 609,
  Hotkey_keycode53                  = 610,
  Hotkey_function53                 = 611,
  Hotkey_keycode54                  = 612,
  Hotkey_function54                 = 613,
  Hotkey_keycode55                  = 614,
  Hotkey_function55                 = 615,
  Hotkey_keycode56                  = 616,
  Hotkey_function56                 = 617,
  Hotkey_keycode57                  = 618,
  Hotkey_function57                 = 619,
  Hotkey_keycode58                  = 620,
  Hotkey_function58                 = 621,
  Hotkey_keycode59                  = 622,
  Hotkey_function59                 = 623,
  Hotkey_keycode60                  = 624,
  Hotkey_function60                 = 625,
  Hotkey_keycode61                  = 626,
  Hotkey_function61                 = 627,
  Hotkey_keycode62                  = 628,
  Hotkey_function62                 = 629,
  Hotkey_keycode63                  = 630,
  Hotkey_function63                 = 631,
  Hotkey_keycode64                  = 632,
  Hotkey_function64                 = 633,
  Hotkey_keycode65                  = 634,
  Hotkey_function65                 = 635,
  Hotkey_keycode66                  = 636,
  Hotkey_function66                 = 637,
  Hotkey_keycode67                  = 638,
  Hotkey_function67                 = 639,
  Hotkey_keycode68                  = 640,
  Hotkey_function68                 = 641,
  Hotkey_keycode69                  = 642,
  Hotkey_function69                 = 643,
  Hotkey_keycode70                  = 644,
  Hotkey_function70                 = 645,
  Hotkey_keycode71                  = 646,
  Hotkey_function71                 = 647,
  Hotkey_keycode72                  = 648,
  Hotkey_function72                 = 649,
  Hotkey_keycode73                  = 650,
  Hotkey_function73                 = 651,
  Hotkey_keycode74                  = 652,
  Hotkey_function74                 = 653,
  Hotkey_keycode75                  = 654,
  Hotkey_function75                 = 655,
  Hotkey_keycode76                  = 656,
  Hotkey_function76                 = 657,
  Hotkey_keycode77                  = 658,
  Hotkey_function77                 = 659,
  Hotkey_keycode78                  = 660,
  Hotkey_function78                 = 661,
  Hotkey_keycode79                  = 662,
  Hotkey_function79                 = 663,
  Hotkey_keycode80                  = 664,
  Hotkey_function80                 = 665,
  Hotkey_keycode81                  = 666,
  Hotkey_function81                 = 667,
  Hotkey_keycode82                  = 668,
  Hotkey_function82                 = 669,
  Hotkey_keycode83                  = 670,
  Hotkey_function83                 = 671,
  Hotkey_keycode84                  = 672,
  Hotkey_function84                 = 673,
  Hotkey_keycode85                  = 674,
  Hotkey_function85                 = 675,
  Hotkey_keycode86                  = 676,
  Hotkey_function86                 = 677,
  Hotkey_keycode87                  = 678,
  Hotkey_function87                 = 679,
  Hotkey_keycode88                  = 680,
  Hotkey_function88                 = 681,
  Hotkey_keycode89                  = 682,
  Hotkey_function89                 = 683,
  Hotkey_keycode90                  = 684,
  Hotkey_function90                 = 685,
  Hotkey_keycode91                  = 886,
  Hotkey_function91                 = 687,
  Hotkey_keycode92                  = 688,
  Hotkey_function92                 = 689,
  Hotkey_keycode93                  = 690,
  Hotkey_function93                 = 691,
  Hotkey_keycode94                  = 692,
  Hotkey_function94                 = 693,
  Hotkey_keycode95                  = 694,
  Hotkey_function95                 = 695,
  Hotkey_keycode96                  = 696,
  Hotkey_function96                 = 697,
  Outputtrigger1pin                 = 700,
  Outputtrigger1port                = 701,
  Outputtrigger1LED                 = 702,
  Outputtrigger2pin                 = 703,
  Outputtrigger2port                = 704,
  Outputtrigger2LED                 = 705,
  Outputtrigger3pin                 = 706,
  Outputtrigger3port                = 707,
  Outputtrigger3LED                 = 708,
  Outputtrigger4pin                 = 709,
  Outputtrigger4port                = 710,
  Outputtrigger4LED                 = 711,
  Outputtrigger5pin                 = 712,
  Outputtrigger5port                = 713,
  Outputtrigger5LED                 = 714,
  Outputtrigger6pin                 = 715,
  Outputtrigger6port                = 716,
  Outputtrigger6LED                 = 717,
  Outputtrigger7pin                 = 718,
  Outputtrigger7port                = 719,
  Outputtrigger7LED                 = 720,
  Outputtrigger8pin                 = 721,
  Outputtrigger8port                = 722,
  Outputtrigger8LED                 = 723,
  Outputtrigger9pin                 = 724,
  Outputtrigger9port                = 725,
  Outputtrigger9LED                 = 726,
  Outputtrigger10pin                = 727,
  Outputtrigger10port               = 728,
  Outputtrigger10LED                = 729,
  Outputtrigger11pin                = 730,
  Outputtrigger11port               = 731,
  Outputtrigger11LED                = 732,
  Outputtrigger12pin                = 733,
  Outputtrigger12port               = 734,
  Outputtrigger12LED                = 735,
  Outputtrigger13pin                = 736,
  Outputtrigger13port               = 737,
  Outputtrigger13LED                = 738,
  Outputtrigger14pin                = 739,
  Outputtrigger14port               = 740,
  Outputtrigger14LED                = 741,
  Outputtrigger15pin                = 742,
  Outputtrigger15port               = 743,
  Outputtrigger15LED                = 744,
  Outputtrigger16pin                = 745,
  Outputtrigger16port               = 746,
  Outputtrigger16LED                = 747,
  Outputtrigger17pin                = 748,
  Outputtrigger17port               = 749,
  Outputtrigger17LED                = 750,
  Outputtrigger18pin                = 751,
  Outputtrigger18port               = 752,
  Outputtrigger18LED                = 753,
  Outputtrigger19pin                = 754,
  Outputtrigger19port               = 755,
  Outputtrigger19LED                = 756,
  Outputtrigger20pin                = 757,
  Outputtrigger20port               = 758,
  Outputtrigger20LED                = 759,
  Outputtrigger21pin                = 760,
  Outputtrigger21port               = 761,
  Outputtrigger21LED                = 762,
  Outputtrigger22pin                = 763,
  Outputtrigger22port               = 764,
  Outputtrigger22LED                = 765,
  Outputtrigger23pin                = 766,
  Outputtrigger23port               = 767,
  Outputtrigger23LED                = 768,
  Outputtrigger24pin                = 769,
  Outputtrigger24port               = 770,
  Outputtrigger24LED                = 771,
  Outputtrigger25pin                = 772,
  Outputtrigger25port               = 773,
  Outputtrigger25LED                = 774,
  Outputtrigger26pin                = 775,
  Outputtrigger26port               = 776,
  Outputtrigger26LED                = 777,
  Outputtrigger27pin                = 778,
  Outputtrigger27port               = 779,
  Outputtrigger27LED                = 780,
  Outputtrigger28pin                = 781,
  Outputtrigger28port               = 782,
  Outputtrigger28LED                = 783,
  Outputtrigger29pin                = 784,
  Outputtrigger29port               = 785,
  Outputtrigger29LED                = 786,
  Outputtrigger30pin                = 787,
  Outputtrigger30port               = 788,
  Outputtrigger30LED                = 789,
  Outputtrigger31pin                = 790,
  Outputtrigger31port               = 791,
  Outputtrigger31LED                = 792,
  Outputtrigger32pin                = 793,
  Outputtrigger32port               = 794,
  Outputtrigger32LED                = 795,
  Outputtrigger33pin                = 796,
  Outputtrigger33port               = 797,
  Outputtrigger33LED                = 798,
  Outputtrigger34pin                = 799,
  Outputtrigger34port               = 800,
  Outputtrigger34LED                = 801,
  Outputtrigger35pin                = 802,
  Outputtrigger35port               = 803,
  Outputtrigger35LED                = 804,
  Outputtrigger36pin                = 805,
  Outputtrigger36port               = 806,
  Outputtrigger36LED                = 807,
  Outputtrigger37pin                = 808,
  Outputtrigger37port               = 809,
  Outputtrigger37LED                = 810,
  Outputtrigger38pin                = 811,
  Outputtrigger38port               = 812,
  Outputtrigger38LED                = 813,
  Outputtrigger39pin                = 814,
  Outputtrigger39port               = 815,
  Outputtrigger39LED                = 816,
  Outputtrigger40pin                = 817,
  Outputtrigger40port               = 818,
  Outputtrigger40LED                = 819,
  Outputtrigger41pin                = 820,
  Outputtrigger41port               = 821,
  Outputtrigger41LED                = 822,
  Outputtrigger42pin                = 823,
  Outputtrigger42port               = 824,
  Outputtrigger42LED                = 825,
  Outputtrigger43pin                = 826,
  Outputtrigger43port               = 827,
  Outputtrigger43LED                = 828,
  Outputtrigger44pin                = 829,
  Outputtrigger44port               = 830,
  Outputtrigger44LED                = 831,
  Outputtrigger45pin                = 832,
  Outputtrigger45port               = 833,
  Outputtrigger45LED                = 834,
  Outputtrigger46pin                = 835,
  Outputtrigger46port               = 836,
  Outputtrigger46LED                = 837,
  Outputtrigger47pin                = 838,
  Outputtrigger47port               = 839,
  Outputtrigger47LED                = 840,
  Outputtrigger48pin                = 841,
  Outputtrigger48port               = 842,
  Outputtrigger48LED                = 843,
  // R* (Reserved)
  EncoderApin                       = 852,
  EncoderAport                      = 853,
  EncoderBpin                       = 854,
  EncoderBport                      = 855,
  CAM_Tooldia                       = 856,
  CAM_Startdepth                    = 857,
  CAM_Cutdepth                      = 858,
  CAM_Cutperpass                    = 859,
  CAM_SafeZ                         = 860,
  CAM_Feedrate                      = 861,
  CAM_Tooloverlap                   = 862,
  CAM_Plungerate                    = 863,
  EncoderPPR                        = 864,
  CAM_Spindlespeed                  = 865,
  Setnextlinefield                  = 866,
  Setfeedrate                       = 867,
  Actfeedrate                       = 868,
  Setspindlespeed                   = 869,
  Actspindlespeed                   = 870,
  MachinecoordX                     = 871,
  MachinecoordY                     = 872,
  MachinecoordZ                     = 873,
  MachinecoordA                     = 874,
  MachinecoordB                     = 875,
  MachinecoordC                     = 876,
  Activemodal                       = 877,
  IOmonitor_XPOS                    = 878,
  IOmonitor_YPOS                    = 879,
  IOmonitor_ZPOS                    = 880,
  IOmonitor_APOS                    = 881,
  IOmonitor_BPOS                    = 882,
  IOmonitor_CPOS                    = 883,
  Motionbuffer                      = 884,
  Diagnostics_minX                  = 885,
  Diagnostics_minY                  = 886,
  Diagnostics_minZ                  = 887,
  Diagnostics_maxX                  = 888,
  Diagnostics_maxY                  = 889,
  Diagnostics_maxZ                  = 890,
  Diagnostics_sizeX                 = 891,
  Diagnostics_sizeY                 = 892,
  Diagnostics_sizeZ                 = 893,
  Diagnostics_totalnumberofobjects  = 894,
  Diagnostics_Filename              = 895,
  Dwell_time                        = 896,
  Active_toolnumber                 = 897,
  Worktimer                         = 898,
  Active_fixture                    = 899,
  Profile_name                      = 900,
  Licensed_to                       = 901,
  Softwareversion                   = 902,
  Firmwareversion                   = 903,
  Hardwareversion                   = 904,
  APIversion                        = 905,
  Serialnumber                      = 906,
  Devicetype                        = 907,
  CAM_Statuslabel                   = 908,
  Analog_inputvalue1                = 909,
  Analog_inputvalue2                = 910,
  Analog_outputvalue1               = 911,
  Analog_outputvalue2               = 912,
  Jogfeedrate                       = 913,
  Laseroutputpin                    = 914,
  Laseroutputport                   = 915,
  // 916-920 R* (Reserved)
  ToolZoffset21                     = 921,
  ToolZoffset22                     = 922,
  ToolZoffset23                     = 923,
  ToolZoffset24                     = 924,
  ToolZoffset25                     = 925,
  ToolZoffset26                     = 926,
  ToolZoffset27                     = 927,
  ToolZoffset28                     = 928,
  ToolZoffset29                     = 929,
  ToolZoffset30                     = 930,
  ToolZoffset31                     = 931,
  ToolZoffset32                     = 932,
  ToolZoffset33                     = 933,
  ToolZoffset34                     = 934,
  ToolZoffset35                     = 935,
  ToolZoffset36                     = 936,
  ToolZoffset37                     = 937,
  ToolZoffset38                     = 938,
  ToolZoffset39                     = 939,
  ToolZoffset40                     = 940,
  ToolZoffset41                     = 941,
  ToolZoffset42                     = 942,
  ToolZoffset43                     = 943,
  ToolZoffset44                     = 944,
  ToolZoffset45                     = 945,
  ToolZoffset46                     = 946,
  ToolZoffset47                     = 947,
  ToolZoffset48                     = 948,
  ToolZoffset49                     = 949,
  ToolZoffset50                     = 950,
  ToolZoffset51                     = 951,
  ToolZoffset52                     = 952,
  ToolZoffset53                     = 953,
  ToolZoffset54                     = 954,
  ToolZoffset55                     = 955,
  ToolZoffset56                     = 956,
  ToolZoffset57                     = 957,
  ToolZoffset58                     = 958,
  ToolZoffset59                     = 959,
  ToolZoffset60                     = 960,
  ToolZoffset61                     = 961,
  ToolZoffset62                     = 962,
  ToolZoffset63                     = 963,
  ToolZoffset64                     = 964,
  ToolZoffset65                     = 965,
  ToolZoffset66                     = 966,
  ToolZoffset67                     = 967,
  ToolZoffset68                     = 968,
  ToolZoffset69                     = 969,
  ToolZoffset70                     = 970,
  ToolZoffset71                     = 971,
  ToolZoffset72                     = 972,
  ToolZoffset73                     = 973,
  ToolZoffset74                     = 974,
  ToolZoffset75                     = 975,
  ToolZoffset76                     = 976,
  ToolZoffset77                     = 977,
  ToolZoffset78                     = 978,
  ToolZoffset79                     = 979,
  ToolZoffset80                     = 980,
  ToolZoffset81                     = 981,
  ToolZoffset82                     = 982,
  ToolZoffset83                     = 983,
  ToolZoffset84                     = 984,
  ToolZoffset85                     = 985,
  ToolZoffset86                     = 986,
  ToolZoffset87                     = 987,
  ToolZoffset88                     = 988,
  ToolZoffset89                     = 989,
  ToolZoffset90                     = 990,
  ToolZoffset91                     = 991,
  ToolZoffset92                     = 992,
  ToolZoffset93                     = 993,
  ToolZoffset94                     = 994,
  ToolZoffset95                     = 995,
  ToolZoffset96                     = 996,
  // R*	949-1000 (reserved)
  Mdi                               = 1000, // Not documented
  // R* 1001-2000 (reserved)
  THCAntidivevelocitypercentage     = 2001,
  Analog_inputvalue3                = 2002,
  Analog_inputvalue4                = 2003,
  Analoginput3var                   = 2004,
  Analoginput4var                   = 2005,
  Analogoutput3var                  = 2006,
  Analogoutput4var                  = 2007,
  Analog_outputvalue3               = 2008,
  Analog_outputvalue4               = 2009,
  Plasmapieceheight                 = 2010,
  Probepin2                         = 2011,
  Probeport2                        = 2012,
  Pulleynumber                      = 2013,
  Pulleyratio                       = 2014,
  Digitize_numberofdigits           = 2015,
  Digitize_proberadius              = 2016,
  Digitize_filename                 = 2017,
  Digitize_numberofstoredpoints     = 2018,
  Chargepump2pin                    = 2019,
  Chargepump2port                   = 2020,
  THCenableoutputpin                = 2021,
  THCenableoutputport               = 2022,
  Antidiveoutputpin                 = 2023,
  Antidiveoutputport                = 2024,
  Antidownoutputpin                 = 2025,
  Antidownoutputport                = 2026,
  JogStepDistance                   = 2027,
  Inputtrigger49pin                 = 2100,
  Inputtrigger49port                = 2101,
  Inputtrigger49function            = 2102,
  Inputtrigger50pin                 = 2103,
  Inputtrigger50port                = 2104,
  Inputtrigger50function            = 2105,
  Inputtrigger51pin                 = 2106,
  Inputtrigger51port                = 2107,
  Inputtrigger51function            = 2108,
  Inputtrigger52pin                 = 2109,
  Inputtrigger52port                = 2110,
  Inputtrigger52function            = 2111,
  Inputtrigger53pin                 = 2112,
  Inputtrigger53port                = 2113,
  Inputtrigger53function            = 2114,
  Inputtrigger54pin                 = 2115,
  Inputtrigger54port                = 2116,
  Inputtrigger54function            = 2117,
  Inputtrigger55pin                 = 2118,
  Inputtrigger55port                = 2119,
  Inputtrigger55function            = 2120,
  Inputtrigger56pin                 = 2121,
  Inputtrigger56port                = 2122,
  Inputtrigger56function            = 2123,
  Inputtrigger57pin                 = 2124,
  Inputtrigger57port                = 2125,
  Inputtrigger57function            = 2126,
  Inputtrigger58pin                 = 2127,
  Inputtrigger58port                = 2128,
  Inputtrigger58function            = 2129,
  Inputtrigger59pin                 = 2130,
  Inputtrigger59port                = 2131,
  Inputtrigger59function            = 2132,
  Inputtrigger60pin                 = 2133,
  Inputtrigger60port                = 2134,
  Inputtrigger60function            = 2135,
  Inputtrigger61pin                 = 2136,
  Inputtrigger61port                = 2137,
  Inputtrigger61function            = 2138,
  Inputtrigger62pin                 = 2139,
  Inputtrigger62port                = 2140,
  Inputtrigger62function            = 2141,
  Inputtrigger63pin                 = 2142,
  Inputtrigger63port                = 2143,
  Inputtrigger63function            = 2144,
  Inputtrigger64pin                 = 2145,
  Inputtrigger64port                = 2146,
  Inputtrigger64function            = 2147,
  Inputtrigger65pin                 = 2148,
  Inputtrigger65port                = 2149,
  Inputtrigger65function            = 2150,
  Inputtrigger66pin                 = 2151,
  Inputtrigger66port                = 2152,
  Inputtrigger66function            = 2153,
  Inputtrigger67pin                 = 2154,
  Inputtrigger67port                = 2155,
  Inputtrigger67function            = 2156,
  Inputtrigger68pin                 = 2157,
  Inputtrigger68port                = 2158,
  Inputtrigger68function            = 2159,
  Inputtrigger69pin                 = 2160,
  Inputtrigger69port                = 2161,
  Inputtrigger69function            = 2162,
  Inputtrigger70pin                 = 2163,
  Inputtrigger70port                = 2164,
  Inputtrigger70function            = 2165,
  Inputtrigger71pin                 = 2166,
  Inputtrigger71port                = 2167,
  Inputtrigger71function            = 2168,
  Inputtrigger72pin                 = 2169,
  Inputtrigger72port                = 2170,
  Inputtrigger72function            = 2171,
  Inputtrigger73pin                 = 2172,
  Inputtrigger73port                = 2173,
  Inputtrigger73function            = 2174,
  Inputtrigger74pin                 = 2175,
  Inputtrigger74port                = 2176,
  Inputtrigger74function            = 2177,
  Inputtrigger75pin                 = 2178,
  Inputtrigger75port                = 2179,
  Inputtrigger75function            = 2180,
  Inputtrigger76pin                 = 2181,
  Inputtrigger76port                = 2182,
  Inputtrigger76function            = 2183,
  Inputtrigger77pin                 = 2184,
  Inputtrigger77port                = 2185,
  Inputtrigger77function            = 2186,
  Inputtrigger78pin                 = 2187,
  Inputtrigger78port                = 2188,
  Inputtrigger78function            = 2189,
  Inputtrigger79pin                 = 2190,
  Inputtrigger79port                = 2191,
  Inputtrigger79function            = 2192,
  Inputtrigger80pin                 = 2193,
  Inputtrigger80port                = 2194,
  Inputtrigger80function            = 2195,
  Inputtrigger81pin                 = 2196,
  Inputtrigger81port                = 2197,
  Inputtrigger81function            = 2198,
  Inputtrigger82pin                 = 2199,
  Inputtrigger82port                = 2200,
  Inputtrigger82function            = 2201,
  Inputtrigger83pin                 = 2202,
  Inputtrigger83port                = 2203,
  Inputtrigger83function            = 2204,
  Inputtrigger84pin                 = 2205,
  Inputtrigger84port                = 2206,
  Inputtrigger84function            = 2207,
  Inputtrigger85pin                 = 2208,
  Inputtrigger85port                = 2209,
  Inputtrigger85function            = 2210,
  Inputtrigger86pin                 = 2211,
  Inputtrigger86port                = 2212,
  Inputtrigger86function            = 2213,
  Inputtrigger87pin                 = 2214,
  Inputtrigger87port                = 2215,
  Inputtrigger87function            = 2216,
  Inputtrigger88pin                 = 2217,
  Inputtrigger88port                = 2218,
  Inputtrigger88function            = 2219,
  Inputtrigger89pin                 = 2220,
  Inputtrigger89port                = 2221,
  Inputtrigger89function            = 2222,
  Inputtrigger90pin                 = 2223,
  Inputtrigger90port                = 2224,
  Inputtrigger90function            = 2225,
  Inputtrigger91pin                 = 2226,
  Inputtrigger91port                = 2227,
  Inputtrigger91function            = 2228,
  Inputtrigger92pin                 = 2229,
  Inputtrigger92port                = 2230,
  Inputtrigger92function            = 2231,
  Inputtrigger93pin                 = 2232,
  Inputtrigger93port                = 2233,
  Inputtrigger93function            = 2234,
  Inputtrigger94pin                 = 2235,
  Inputtrigger94port                = 2236,
  Inputtrigger94function            = 2237,
  Inputtrigger95pin                 = 2238,
  Inputtrigger95port                = 2239,
  Inputtrigger95function            = 2240,
  Inputtrigger96pin                 = 2241,
  Inputtrigger96port                = 2242,
  Inputtrigger96function            = 2243,
  Outputtrigger49pin                = 2250,
  Outputtrigger49port               = 2251,
  Outputtrigger49LED                = 2252,
  Outputtrigger50pin                = 2253,
  Outputtrigger50port               = 2254,
  Outputtrigger50LED                = 2255,
  Outputtrigger51pin                = 2256,
  Outputtrigger51port               = 2257,
  Outputtrigger51LED                = 2258,
  Outputtrigger52pin                = 2259,
  Outputtrigger52port               = 2260,
  Outputtrigger52LED                = 2261,
  Outputtrigger53pin                = 2262,
  Outputtrigger53port               = 2263,
  Outputtrigger53LED                = 2264,
  Outputtrigger54pin                = 2265,
  Outputtrigger54port               = 2266,
  Outputtrigger54LED                = 2267,
  Outputtrigger55pin                = 2268,
  Outputtrigger55port               = 2269,
  Outputtrigger55LED                = 2270,
  Outputtrigger56pin                = 2271,
  Outputtrigger56port               = 2272,
  Outputtrigger56LED                = 2273,
  Outputtrigger57pin                = 2274,
  Outputtrigger57port               = 2275,
  Outputtrigger57LED                = 2276,
  Outputtrigger58pin                = 2277,
  Outputtrigger58port               = 2278,
  Outputtrigger58LED                = 2279,
  Outputtrigger59pin                = 2280,
  Outputtrigger59port               = 2281,
  Outputtrigger59LED                = 2282,
  Outputtrigger60pin                = 2283,
  Outputtrigger60port               = 2284,
  Outputtrigger60LED                = 2285,
  Outputtrigger61pin                = 2286,
  Outputtrigger61port               = 2287,
  Outputtrigger61LED                = 2288,
  Outputtrigger62pin                = 2289,
  Outputtrigger62port               = 2290,
  Outputtrigger62LED                = 2291,
  Outputtrigger63pin                = 2292,
  Outputtrigger63port               = 2293,
  Outputtrigger63LED                = 2294,
  Outputtrigger64pin                = 2295,
  Outputtrigger64port               = 2296,
  Outputtrigger64LED                = 2297,
  Outputtrigger65pin                = 2298,
  Outputtrigger65port               = 2299,
  Outputtrigger65LED                = 2300,
  Outputtrigger66pin                = 2301,
  Outputtrigger66port               = 2302,
  Outputtrigger66LED                = 2303,
  Outputtrigger67pin                = 2304,
  Outputtrigger67port               = 2305,
  Outputtrigger67LED                = 2306,
  Outputtrigger68pin                = 2307,
  Outputtrigger68port               = 2308,
  Outputtrigger68LED                = 2309,
  Outputtrigger69pin                = 2310,
  Outputtrigger69port               = 2311,
  Outputtrigger69LED                = 2312,
  Outputtrigger70pin                = 2313,
  Outputtrigger70port               = 2314,
  Outputtrigger70LED                = 2315,
  Outputtrigger71pin                = 2316,
  Outputtrigger71port               = 2317,
  Outputtrigger71LED                = 2318,
  Outputtrigger72pin                = 2319,
  Outputtrigger72port               = 2320,
  Outputtrigger72LED                = 2321,
  Outputtrigger73pin                = 2322,
  Outputtrigger73port               = 2323,
  Outputtrigger73LED                = 2324,
  Outputtrigger74pin                = 2325,
  Outputtrigger74port               = 2326,
  Outputtrigger74LED                = 2327,
  Outputtrigger75pin                = 2328,
  Outputtrigger75port               = 2329,
  Outputtrigger75LED                = 2330,
  Outputtrigger76pin                = 2331,
  Outputtrigger76port               = 2332,
  Outputtrigger76LED                = 2333,
  Outputtrigger77pin                = 2334,
  Outputtrigger77port               = 2335,
  Outputtrigger77LED                = 2336,
  Outputtrigger78pin                = 2337,
  Outputtrigger78port               = 2338,
  Outputtrigger78LED                = 2339,
  Outputtrigger79pin                = 2340,
  Outputtrigger79port               = 2341,
  Outputtrigger79LED                = 2342,
  Outputtrigger80pin                = 2343,
  Outputtrigger80port               = 2344,
  Outputtrigger80LED                = 2345,
  Outputtrigger81pin                = 2346,
  Outputtrigger81port               = 2347,
  Outputtrigger81LED                = 2348,
  Outputtrigger82pin                = 2349,
  Outputtrigger82port               = 2350,
  Outputtrigger82LED                = 2351,
  Outputtrigger83pin                = 2352,
  Outputtrigger83port               = 2353,
  Outputtrigger83LED                = 2354,
  Outputtrigger84pin                = 2355,
  Outputtrigger84port               = 2356,
  Outputtrigger84LED                = 2357,
  Outputtrigger85pin                = 2358,
  Outputtrigger85port               = 2359,
  Outputtrigger85LED                = 2360,
  Outputtrigger86pin                = 2361,
  Outputtrigger86port               = 2362,
  Outputtrigger86LED                = 2363,
  Outputtrigger87pin                = 2364,
  Outputtrigger87port               = 2365,
  Outputtrigger87LED                = 2366,
  Outputtrigger88pin                = 2367,
  Outputtrigger88port               = 2368,
  Outputtrigger88LED                = 2369,
  Outputtrigger89pin                = 2370,
  Outputtrigger89port               = 2371,
  Outputtrigger89LED                = 2372,
  Outputtrigger90pin                = 2373,
  Outputtrigger90port               = 2374,
  Outputtrigger90LED                = 2375,
  Outputtrigger91pin                = 2376,
  Outputtrigger91port               = 2377,
  Outputtrigger91LED                = 2378,
  Outputtrigger92pin                = 2379,
  Outputtrigger92port               = 2380,
  Outputtrigger92LED                = 2381,
  Outputtrigger93pin                = 2382,
  Outputtrigger93port               = 2383,
  Outputtrigger93LED                = 2384,
  Outputtrigger94pin                = 2385,
  Outputtrigger94port               = 2386,
  Outputtrigger94LED                = 2387,
  Outputtrigger95pin                = 2388,
  Outputtrigger95port               = 2389,
  Outputtrigger95LED                = 2390,
  Outputtrigger96pin                = 2391,
  Outputtrigger96port               = 2392,
  Outputtrigger96LED                = 2393,
  AUXencoder1pinA                   = 2400,
  AUXencoder1portA                  = 2401,
  AUXencoder1pinB                   = 2402,
  AUXencoder1portB                  = 2403,
  AUXencoder2pinA                   = 2404,
  AUXencoder2portA                  = 2405,
  AUXencoder2pinB                   = 2406,
  AUXencoder2portB                  = 2407,
  AUXencoder3pinA                   = 2408,
  AUXencoder3portA                  = 2409,
  AUXencoder3pinB                   = 2410,
  AUXencoder3portB                  = 2411,
  AUXencoder4pinA                   = 2412,
  AUXencoder4portA                  = 2413,
  AUXencoder4pinB                   = 2414,
  AUXencoder4portB                  = 2415,
  AUXencoder5pinA                   = 2416,
  AUXencoder5portA                  = 2417,
  AUXencoder5pinB                   = 2418,
  AUXencoder5portB                  = 2419,
  AUXencoder6pinA                   = 2420,
  AUXencoder6portA                  = 2421,
  AUXencoder6pinB                   = 2422,
  AUXencoder6portB                  = 2423,
  AUXencoder1countsper              = 2424,
  AUXencoder2countsper              = 2425,
  AUXencoder3countsper              = 2426,
  AUXencoder4countsper              = 2427,
  AUXencoder5countsper              = 2428,
  AUXencoder6countsper              = 2429,
  AUXencoder1position               = 2430,
  AUXencoder2position               = 2431,
  AUXencoder3position               = 2432,
  AUXencoder4position               = 2433,
  AUXencoder5position               = 2434,
  AUXencoder6position               = 2435,
  SpindlePIDoutputpercentvalue      = 2436,
  Arcradiustolerance                = 2437,
};

//--------------------------------------------------------------------------------------------------------------
// UccncLed
//--------------------------------------------------------------------------------------------------------------

enum class UccncLed : int {
  OutputPT1PN1            = 1,	  // Indicates the actual logic state of port#1 pin#1.
  OutputPT1PN2            = 2,	  // Indicates the actual logic state of port#1 pin#2.
  OutputPT1PN3            = 3,	  // Indicates the actual logic state of port#1 pin#3.
  OutputPT1PN4            = 4,	  // Indicates the actual logic state of port#1 pin#4.
  OutputPT1PN5            = 5,	  // Indicates the actual logic state of port#1 pin#5.
  OutputPT1PN6            = 6,	  // Indicates the actual logic state of port#1 pin#6.
  OutputPT1PN7            = 7,	  // Indicates the actual logic state of port#1 pin#7.
  OutputPT1PN8            = 8,	  // Indicates the actual logic state of port#1 pin#8.
  OutputPT1PN9            = 9,	  // Indicates the actual logic state of port#1 pin#9.
  OutputPT1PN10           = 10,	  // Indicates the actual logic state of port#1 pin#10.
  OutputPT1PN11           = 11,	  // Indicates the actual logic state of port#1 pin#11.
  OutputPT1PN12           = 12,	  // Indicates the actual logic state of port#1 pin#12.
  OutputPT1PN13           = 13,	  // Indicates the actual logic state of port#1 pin#13.
  OutputPT1PN14           = 14,	  // Indicates the actual logic state of port#1 pin#14.
  OutputPT1PN15           = 15,	  // Indicates the actual logic state of port#1 pin#15.
  OutputPT1PN16           = 16,	  // Indicates the actual logic state of port#1 pin#16.
  OutputPT1PN17           = 17,	  // Indicates the actual logic state of port#1 pin#17.
  Idle                    = 18,	  // Indicates the Idle state of the device.
  Run                     = 19,	  // Indicates a run state of the device. This is the opposite of the Idle state.
  Jog                     = 20,	  // Active when a jog command is being executed.
  Dwell                   = 21,	  // Indicates a dwell in progress.
  Backlash                = 22,	  // Active when the backlash compensation is being executed.
  Home                    = 23,	  // Active when the homing command is being executed.
  Probing                 = 24,	  // Active when the probing command is being executed.
  Reset                   = 25,	  // Indicates an active reset signal.
  Hardlimit               = 26,	  // Active when any of the configured limit inputs are triggered.
  Limitsoverride          = 27,	  // Active if the limits are overriden by the user.
  Toolchangeinprogress    = 28,	  // Active when a tool change macro is being executed.
  Xlimitpositive          = 29,	  // Active when the X-axis positive side limit switch is triggered.
  Ylimitpositive          = 30,	  // Active when the Y-axis positive side limit switch is triggered.
  Zlimitpositive          = 31,	  // Active when the Z-axis positive side limit switch is triggered.
  Alimitpositive          = 32,	  // Active when the A-axis positive side limit switch is triggered.
  Blimitpositive          = 33,	  // Active when the B-axis positive side limit switch is triggered.
  Climitpositive          = 34,	  // Active when the C-axis positive side limit switch is triggered.
  Index                   = 35,	  // Active when the index input is triggered.
  Estop                   = 36,	  // Active when the estop input is triggered.
  Probe                   = 37,	  // Active when the probe input is triggered.
  Xlimitnegative          = 38,	  // Active when the X-axis negative side limit switch is triggered.
  Ylimitnegative          = 39,	  // Active when the Y-axis negative side limit switch is triggered.
  Zlimitnegative          = 40,	  // Active when the Z-axis negative side limit switch is triggered.
  Alimitnegative          = 41,	  // Active when the A-axis negative side limit switch is triggered.
  Blimitnegative          = 42,	  // Active when the B-axis negative side limit switch is triggered.
  Climitnegative          = 43,	  // Active when the C-axis negative side limit switch is triggered.
  Xhome                   = 44,	  // Active when then X-axis home input is triggered.
  Yhome                   = 45,	  // Active when then Y-axis home input is triggered.
  Zhome                   = 46,	  // Active when then Z-axis home input is triggered.
  Ahome                   = 47,	  // Active when then A-axis home input is triggered.
  Bhome                   = 48,	  // Active when then B-axis home input is triggered.
  Chome                   = 49,	  // Active when then C-axis home input is triggered.
  SpindleCW               = 50,	  // Active when the spindle is rotating Clockwise.
  SpindleCCW              = 51,	  // Active when the spindle is rotating Counter-clockwise
  Miston                  = 52,	  // Active when the mist coolant is on.
  Floodon                 = 53,	  // Active when the flood coolant is on.
  Cyclestart              = 54,	  // Active when a G-code execution cycle is in progress.
  Runsingleline           = 55,	  // Active when a Single line G-code execution cycle is in progress.
  Xhomed                  = 56,	  // Active when the X-axis was already homed.
  Yhomed                  = 57,	  // Active when the Y-axis was already homed.
  Zhomed                  = 58,	  // Active when the Z-axis was already homed.
  Ahomed                  = 59,	  // Active when the A-axis was already homed.
  Bhomed                  = 60,	  // Active when the B-axis was already homed.
  Chomed                  = 61,	  // Active when the C-axis was already homed.
  Machinecoords           = 62,	  // Active when the machine coordinate system is selected to view in the position
                                  // DROs.
  THCon                   = 63,	  // Active when the THC on physical input is active.
  THCup                   = 64,	  // Active when the THC up physical input is active.
  THCdown                 = 65,	  // Active when the THC down physical input is active.
  THCenabled              = 66,	  // Active when the THC control is enabled.
  Softlimitsenabled       = 67,	  // Active when the Software limit function is enabled.
  THCdelay                = 68,	  // Active when the THC delay is ongoing.
  OutputPT2PN1            = 69,	  // Indicates the actual logic state of port#2 pin#1.
  OutputPT2PN2            = 70,	  // Indicates the actual logic state of port#2 pin#2.
  OutputPT2PN3            = 71,	  // Indicates the actual logic state of port#2 pin#3.
  OutputPT2PN4            = 72,	  // Indicates the actual logic state of port#2 pin#4.
  OutputPT2PN5            = 73,	  // Indicates the actual logic state of port#2 pin#5.
  OutputPT2PN6            = 74,	  // Indicates the actual logic state of port#2 pin#6.
  OutputPT2PN7            = 75,	  // Indicates the actual logic state of port#2 pin#7.
  OutputPT2PN8            = 76,	  // Indicates the actual logic state of port#2 pin#8.
  OutputPT2PN9            = 77,	  // Indicates the actual logic state of port#2 pin#9.
  OutputPT2PN10           = 78,	  // Indicates the actual logic state of port#2 pin#10.
  OutputPT2PN11           = 79,	  // Indicates the actual logic state of port#2 pin#11.
  OutputPT2PN12           = 80,	  // Indicates the actual logic state of port#2 pin#12.
  OutputPT2PN13           = 81,	  // Indicates the actual logic state of port#2 pin#13.
  OutputPT2PN14           = 82,	  // Indicates the actual logic state of port#2 pin#14.
  OutputPT2PN15           = 83,	  // Indicates the actual logic state of port#2 pin#15.
  OutputPT2PN16           = 84,	  // Indicates the actual logic state of port#2 pin#16.
  OutputPT2PN17           = 85,	  // Indicates the actual logic state of port#2 pin#17.
  OutputPT3PN1            = 86,	  // Indicates the actual logic state of port#3 pin#1.
  OutputPT3PN2            = 87,	  // Indicates the actual logic state of port#3 pin#2.
  OutputPT3PN3            = 88,	  // Indicates the actual logic state of port#3 pin#3.
  OutputPT3PN4            = 89,	  // Indicates the actual logic state of port#3 pin#4.
  OutputPT3PN5            = 90,	  // Indicates the actual logic state of port#3 pin#5.
  OutputPT3PN6            = 91,	  // Indicates the actual logic state of port#3 pin#6.
  OutputPT3PN7            = 92,	  // Indicates the actual logic state of port#3 pin#7.
  OutputPT3PN8            = 93,	  // Indicates the actual logic state of port#3 pin#8.
  OutputPT3PN9            = 94,	  // Indicates the actual logic state of port#3 pin#9.
  OutputPT3PN10           = 95,	  // Indicates the actual logic state of port#3 pin#10.
  OutputPT3PN11           = 96,	  // Indicates the actual logic state of port#3 pin#11.
  OutputPT3PN12           = 97,	  // Indicates the actual logic state of port#3 pin#12.
  OutputPT3PN13           = 98,	  // Indicates the actual logic state of port#3 pin#13.
  OutputPT3PN14           = 99,	  // Indicates the actual logic state of port#3 pin#14.
  OutputPT3PN15           = 100,	// Indicates the actual logic state of port#3 pin#15.
  OutputPT3PN16           = 101,	// Indicates the actual logic state of port#3 pin#16.
  OutputPT3PN17           = 102,	// Indicates the actual logic state of port#3 pin#17.
  OutputPT4PN1            = 103,	// Indicates the actual logic state of port#4 pin#1.
  OutputPT4PN2            = 104,	// Indicates the actual logic state of port#4 pin#2.
  OutputPT4PN3            = 105,	// Indicates the actual logic state of port#4 pin#3.
  OutputPT4PN4            = 106,	// Indicates the actual logic state of port#4 pin#4.
  OutputPT4PN5            = 107,	// Indicates the actual logic state of port#4 pin#5.
  OutputPT4PN6            = 108,	// Indicates the actual logic state of port#4 pin#6.
  OutputPT4PN7            = 109,	// Indicates the actual logic state of port#4 pin#7.
  OutputPT4PN8            = 110,	// Indicates the actual logic state of port#4 pin#8.
  OutputPT4PN9            = 111,	// Indicates the actual logic state of port#4 pin#9.
  OutputPT4PN10           = 112,	// Indicates the actual logic state of port#4 pin#10.
  OutputPT4PN11           = 113,	// Indicates the actual logic state of port#4 pin#11.
  OutputPT4PN12           = 114,	// Indicates the actual logic state of port#4 pin#12.
  OutputPT4PN13           = 115,	// Indicates the actual logic state of port#4 pin#13.
  OutputPT4PN14           = 116,	// Indicates the actual logic state of port#4 pin#14.
  OutputPT4PN15           = 117,	// Indicates the actual logic state of port#4 pin#15.
  OutputPT4PN16           = 118,	// Indicates the actual logic state of port#4 pin#16.
  OutputPT4PN17           = 119,	// Indicates the actual logic state of port#4 pin#17.
  OutputPT5PN1            = 120,	// Indicates the actual logic state of port#5 pin#1.
  OutputPT5PN2            = 121,	// Indicates the actual logic state of port#5 pin#2.
  OutputPT5PN3            = 122,	// Indicates the actual logic state of port#5 pin#3.
  OutputPT5PN4            = 123,	// Indicates the actual logic state of port#5 pin#4.
  OutputPT5PN5            = 124,	// Indicates the actual logic state of port#5 pin#5.
  OutputPT5PN6            = 125,	// Indicates the actual logic state of port#5 pin#6.
  OutputPT5PN7            = 126,	// Indicates the actual logic state of port#5 pin#7.
  OutputPT5PN8            = 127,	// Indicates the actual logic state of port#5 pin#8.
  OutputPT5PN9            = 128,	// Indicates the actual logic state of port#5 pin#9.
  OutputPT5PN10           = 129,	// Indicates the actual logic state of port#5 pin#10.
  OutputPT5PN11           = 130,	// Indicates the actual logic state of port#5 pin#11.
  OutputPT5PN12           = 131,	// Indicates the actual logic state of port#5 pin#12.
  OutputPT5PN13           = 132,	// Indicates the actual logic state of port#5 pin#13.
  OutputPT5PN14           = 133,	// Indicates the actual logic state of port#5 pin#14.
  OutputPT5PN15           = 134,	// Indicates the actual logic state of port#5 pin#15.
  OutputPT5PN16           = 135,	// Indicates the actual logic state of port#5 pin#16.
  OutputPT5PN17           = 136,	// Indicates the actual logic state of port#5 pin#17.
  MPGAPIN                 = 137,	// Indicates the logic state of the MPG A pin.
  MPGBPIN                 = 138,	// Indicates the logic state of the MPG B pin.
  EnableXaxis             = 139,	// On when the enable output of the X axis is active
  EnableYaxis             = 140,	// On when the enable output of the Y axis is active
  EnableZaxis             = 141,	// On when the enable output of the Z axis is active
  EnableAaxis             = 142,	// On when the enable output of the A axis is active
  EnableBaxis             = 143,	// On when the enable output of the B axis is active
  EnableCaxis             = 144,	// On when the enable output of the C axis is active
  Jogmodecontinous        = 145,	// On when the continous jog mode is selected.
  Jogmodestep             = 146,	// On when the step jog mode is selected.
  // R*                   = 147,	// Reserved
  Jograte0001             = 148,	// On when the step jog rate is set to 0.001 units.
  Jograte0010             = 149,	// On when the step jog rate is set to 0.01 units.
  Jograte0100             = 150,	// On when the step jog rate is set to 0.1 units.
  Jograte1000             = 151,	// On when the step jog rate is set to 1 units.
  MPGmodecont             = 152,	// On when the MPG continous mode is selected.
  MPGmodesingle           = 153,	// On when the MPG single mode is selected.
  MPGmodemulti            = 154,	// On when the MPG multi mode is selected.
  MPGXaxisselect          = 155,	// On when the X axis is selected for the MPG jog.
  MPGYaxisselect          = 156,	// On when the Y axis is selected for the MPG jog.
  MPGZaxisselect          = 157,	// On when the Z axis is selected for the MPG jog.
  MPGAaxisselect          = 158,	// On when the A axis is selected for the MPG jog.
  MPGBaxisselect          = 159,	// On when the B axis is selected for the MPG jog.
  MPGCaxisselect          = 160,	// On when the C axis is selected for the MPG jog.
  TABlayervisible         = 161,	// On when the tab layer is visible. The layer number selected is the LED
                                  // code - 161, so the 161. LED code is for the tab layer 0. and the 211. LED
                                  // code is for the 50. tab layer. Note: When more than one tab layer is
                                  // visible, for example if a tab layer has a sub-tab layer which is also
                                  // visible then both LED codes are active.
  // 162 - 211 (see TABlayervisible)
  Offlinemode             = 212,	// On when the offline mode is active.
  Sync_thread             = 213,	// Active when a syncronous thread cutting is in execution.
  EncoderApin             = 214,	// Indicates the logic state of the Encoder A pin.
  EncoderBpin             = 215,	// Indicates the logic state of the Encoder B pin.
  MDIrunning              = 216,	// On when an MDI command is in progress.
  Feedhold                = 217,	// On when the feedhold button is avtice.
  Isdemomode              = 218,	// On if the software is running in demo mode.
  Laserdataloaded         = 219,	// On if a laser data object is loaded to the memory for laser engraving.
  Laserrunning            = 220,	// On when a laser engraving is in progress using the laser data object.
  OutputPT5PN26           = 221,	// Indicates the actual logic state of port#5 pin#26. (M44 motherboard only.)
  OutputPT5PN27           = 222,	// Indicates the actual logic state of port#5 pin#27. (M44 motherboard only.)
  OutputPT5PN28           = 223,	// Indicates the actual logic state of port#5 pin#28. (M44 motherboard only.)
  OutputPT5PN29           = 224,	// Indicates the actual logic state of port#5 pin#29. (M44 motherboard only.)
  OutputPT5PN30           = 225,	// Indicates the actual logic state of port#5 pin#30. (M44 motherboard only.)
  OutputPT5PN31           = 226,	// Indicates the actual logic state of port#5 pin#31. (M44 motherboard only.)
  OutputPT5PN32           = 227,	// Indicates the actual logic state of port#5 pin#32. (M44 motherboard only.)
  OutputPT5PN33           = 228,	// Indicates the actual logic state of port#5 pin#33. (M44 motherboard only.)
  M0stopactive            = 229,	// Indicates that the M0 stop is active.
  M1stopactive            = 230,	// Indicates that the M1 stop is active.
  M60stopactive           = 231,	// Indicates that the M60 stop is active.
  Pause                   = 232,	// On when any of the M0 or M1 or M60 stop mode is active.
  THCAntidiveactive       = 233,	// On when in THC control and the Anti diving happens.
  OutputPT1PN94           = 234,	// Indicates the actual logic state of port#1 pin#94. (5441 motherboard only.)
  OutputPT1PN95           = 235,	// Indicates the actual logic state of port#1 pin#95. (5441 motherboard only.)
  MPGJogOn                = 236,	// Indicates that the MPG jogging is active.
  THCarcon_emulation      = 237,	// Indicates that the THCarcon emulation signal is active.
  THCup_emulation         = 238,	// Indicates that the THCup emulation signal is active.
  THCdown_emulation       = 239,	// Indicates that the THCdown emulation signal is active.
  THCantidiveenabled      = 240,	// On when the THC anti dive function is enabled.
  THCdelayenabled         = 241,	// On when the THC delay function is enabled.
  THCantidownenabled      = 242,	// On when the THC anti down function is enabled.
  SafeProbeModeactive     = 243,	// On when the SafeProbeMode is active. The safe probe mode actives the Reset
                                  // if the probe goes on when not probing.
  ProbedOK                = 244,	// On if the last probing (G31) was finished with a probe touch, off if the
                                  // last probing did not end with a touch.
  Digitizing              = 245,	// On when the M40 digitizing command is active.
  JogSafeProbeModeactive  = 246,	// On when the JogSafeProbeMode is active. The jog safe probe mode stops the
                                  // jog motion if the probe goes on while jogging.
  M1optionalstopenabled   = 247,	// On when the M1 optional stop is enabled
};

//--------------------------------------------------------------------------------------------------------------
// UccncButton
//--------------------------------------------------------------------------------------------------------------

enum class UccncButton : int {
  ZeroX                           = 100, // Zeros the X axis position.
  ZeroY                           = 101, // Zeros the Y axis position.
  ZeroZ                           = 102, // Zeros the Z axis position.
  ZeroA                           = 103, // Zeros the A axis position.
  ZeroB                           = 104, // Zeros the B axis position.
  ZeroC                           = 105, // Zeros the C axis position.
  ZeroAll                         = 106, // Zeros All axis position.
  HomeX                           = 107, // Runs the X axis to the home sensor.
  HomeY                           = 108, // Runs the Y axis to the home sensor.
  HomeZ                           = 109, // Runs the Z axis to the home sensor.
  HomeA                           = 110, // Runs the A axis to the home sensor.
  HomeB                           = 111, // Runs the B axis to the home sensor.
  HomeC                           = 112, // Runs the C axis to the home sensor.
  HomeAll                         = 113, // Runs all axis to the home sensor. The homing sequence is defined in the setup.
  M3toggle                        = 114, // Toggles the M3 spindle CW button.
  M4toggle                        = 115, // Toggles the M4 spindle CCW button.
  M7toggle                        = 116, // Toggles the M7 mist button.
  M8toggle                        = 117, // Toggles the M8 flood button.
  G54select                       = 118, // Selects the G54 coordinate offset.
  G55select                       = 119, // Selects the G55 coordinate offset.
  G56select                       = 120, // Selects the G56 coordinate offset.
  G57select                       = 121, // Selects the G57 coordinate offset.
  G58select                       = 122, // Selects the G58 coordinate offset.
  G59select                       = 123, // Selects the G59 coordinate offset.
  OpenGcodefile                   = 124, // Starts an Open G-code file dialog.
  CloseGcodefile                  = 125, // Closes the G-code file which is loaded.
  EditGcodefile                   = 126, // Opens the notepad to edit the loaded G-code file.
  RewindGcodefile                 = 127, // Rewinds the loaded G-code file with jumping to the first row in the file.
  Cyclestart                      = 128, // Makes a cyclic run on the loaded G-code file.
  Runsingleline                   = 129, // Executes one line of code (the actual code line) of the loaded G-code file.
  Cyclestop                       = 130, // Stops the G-code execution.
  Gotozero                        = 131, // Moves all axis to the zero position with a rapid linear interpolation movement.
  FROincrease                     = 132, // Increases the Feedrate override value.
  FROdecrease                     = 133, // Decreases the Feedrate override value.
  SROincrease                     = 134, // Increases the spindle speed override value.
  SROdecrease                     = 135, // Decreases the spindle speed override value.
  Toolpathzoomin                  = 136, // Zooms in the toolpath viewer.
  Toolpathzoomout                 = 137, // Zooms out the toolpath viewer.
  Toolpathzoomcontents            = 138, // Zooms the contents in the toolpath viewer.
  Toolpathview45                  = 139, // Sets the toolpath to a 45° look viewing mode.
  Toolpathviewright               = 140, // Sets the toolpath to a right side look viewing mode.
  Toolpathviewleft                = 141, // Sets the toolpath to a left side look viewing mode.
  Toolpathviewtop                 = 142, // Sets the toolpath to a top side look viewing mode.
  ToolpathviewISO                 = 143, // Sets the toolpath to Isometric viewing mode.
  Resettoggle                     = 144, // Toggles the reset button.
  Offlinetoggle                   = 145, // Toggles the offline button.
  Limitsoverridetoggle            = 146, // Toggles the limits override button.
  JogXpositive                    = 147, // Jogs the X axis to positive direction.
  JogXnegative                    = 148, // Jogs the X axis to negative direction.
  JogYpositive                    = 149, // Jogs the Y axis to positive direction.
  JogYnegative                    = 150, // Jogs the Y axis to negative direction.
  JogZpositive                    = 151, // Jogs the Z axis to positive direction.
  JogZnegative                    = 152, // Jogs the Z axis to negative direction.
  JogApositive                    = 153, // Jogs the A axis to positive direction.
  JogAnegative                    = 154, // Jogs the A axis to negative direction.
  JogBpositive                    = 155, // Jogs the B axis to positive direction.
  JogBnegative                    = 156, // Jogs the B axis to negative direction.
  JogCpositive                    = 157, // Jogs the C axis to positive direction.
  JogCnegative                    = 158, // Jogs the C axis to negative direction.
  Jograteincrease                 = 159, // Increases the jog rate.
  Jogratedecrease                 = 160, // Decreases the jog rate.
  Jogmodecont                     = 161, // Sets the jog mode to continous.
  Jogmodestep                     = 162, // Sets the jog mode to stepping.
  // R*	(reserved)
  Jogsteprate001                  = 164, // Sets the jog distance when stepping mode to 0.01 Units.
  Jogsteprate010                  = 165, // Sets the jog distance when stepping mode to 0.10 Units.
  Jogsteprate100                  = 166, // Sets the jog distance when stepping mode to 1.00 Units.
  Savesettings                    = 167, // Saves all settings to the profile file.
  Applysettings                   = 168, // Applies the settings on the setup screens.
  Setnextline                     = 169, // Sets the G-code execution pointer to the line defined on the screen in the 128. labelfield.
  G54offsetcurrentpos             = 170, // Offsets the actual position of the G54 coordinate system.
  G55offsetcurrentpos             = 171, // Offsets the actual position of the G55 coordinate system.
  G56offsetcurrentpos             = 172, // Offsets the actual position of the G56 coordinate system.
  G57offsetcurrentpos             = 173, // Offsets the actual position of the G57 coordinate system.
  G58offsetcurrentpos             = 174, // Offsets the actual position of the G58 coordinate system.
  G59offsetcurrentpos             = 175, // Offsets the actual position of the G59 coordinate system.
  G54offsetclear                  = 176, // Clears the offset in the G54 coordinate system.
  G55offsetclear                  = 177, // Clears the offset in the G55 coordinate system.
  G56offsetclear                  = 178, // Clears the offset in the G56 coordinate system.
  G57offsetclear                  = 179, // Clears the offset in the G57 coordinate system.
  G58offsetclear                  = 180, // Clears the offset in the G58 coordinate system.
  G59offsetclear                  = 181, // Clears the offset in the G59 coordinate system.
  Tooloffsetclear1                = 182, // Clears the tool offset.
  Tooloffsetclear2                = 183, // Clears the tool offset.
  Tooloffsetclear3                = 184, // Clears the tool offset.
  Tooloffsetclear4                = 185, // Clears the tool offset.
  Tooloffsetclear5                = 186, // Clears the tool offset.
  Tooloffsetclear6                = 187, // Clears the tool offset.
  Listprofiles                    = 188, // Lists the available profile file names in the 1.Listcomponent.
  Deleteprofile                   = 189, // Deletes the actually selected profile file.
  Loadprofile                     = 190, // Loads the actually selected profile file.
  Createnewprofile                = 191, // Create a new profile, the name of the profile is held in the 216.inputfield.
  DoXMLimport                     = 192, // Imports a Mach3 .xml setup file. The function start an open file dialog.
  Gotoparkposition1               = 193, // Commands the machine to park position 1. (Code executed in Macro M200)
  Gotoparkposition2               = 194, // Commands the machine to park position 2. (Code executed in Macro M201)
  Gotoparkposition3               = 195, // Commands the machine to park position 3. (Code executed in Macro M202)
  Toollengthmeasurement           = 196, // Commands a tool length measurement. (Code executed in Macro M31)
  Machinecoordstoggle             = 197, // Toggles the position DROs between the machine coordinates and the actual offset coordinates view.
  CalibrateX                      = 198, // Calibrates the steps per units value with travel measurement for the X-axis.
  CalibrateY                      = 199, // Calibrates the steps per units value with travel measurement for the Y-axis.
  CalibrateZ                      = 200, // Calibrates the steps per units value with travel measurement for the Z-axis.
  CalibrateA                      = 201, // Calibrates the steps per units value with travel measurement for the A-axis.
  CalibrateB                      = 202, // Calibrates the steps per units value with travel measurement for the B-axis.
  CalibrateC                      = 203, // Calibrates the steps per units value with travel measurement for the C-axis.
  Softlimitstoggle                = 204, // Toggles the software limits enable function.
  THCtoggle                       = 205, // Toggles the THC control enable function.
  Zeroworktimer                   = 218, // Zeros the work timer.
  ClearG92offset                  = 219, // Clears the G92 offset coordinates.
  MPGXaxisselect                  = 220, // Selects the X axis for the MPG jog.
  MPGYaxisselect                  = 221, // Selects the Y axis for the MPG jog.
  MPGZaxisselect                  = 222, // Selects the Z axis for the MPG jog.
  MPGAaxisselect                  = 223, // Selects the A axis for the MPG jog.
  MPGBaxisselect                  = 224, // Selects the B axis for the MPG jog.
  MPGCaxisselect                  = 225, // Selects the C axis for the MPG jog.
  MPGcontmodeselect               = 226, // Selects the continous jog mode for the MPG.
  MPGsinglemodeselect             = 227, // Selects the single step jog mode for the MPG.
  MPGmultimodeselect              = 228, // Selects the multi step jog mode for the MPG.
  JogXplusoff                     = 229, // Switches the X axis positive direction jogging off.
  JogXminusoff                    = 230, // Switches the X axis negative direction jogging off.
  JogYplusoff                     = 231, // Switches the Y axis positive direction jogging off.
  JogYminusoff                    = 232, // Switches the Y axis negative direction jogging off.
  JogZplusoff                     = 233, // Switches the Z axis positive direction jogging off.
  JogZminusoff                    = 234, // Switches the Z axis negative direction jogging off.
  JogAplusoff                     = 235, // Switches the A axis positive direction jogging off.
  JogAminusoff                    = 236, // Switches the A axis negative direction jogging off.
  JogBplusoff                     = 237, // Switches the B axis positive direction jogging off.
  JogBminusoff                    = 238, // Switches the B axis negative direction jogging off.
  JogCplusoff                     = 239, // Switches the C axis positive direction jogging off.
  JogCminusoff                    = 240, // Switches the C axis negative direction jogging off.
  Jogsteprate0001                 = 241, // Sets the jog distance when stepping mode to 0.001 Units.
  Sethotkeycodes1to48             = 242, // to 292	Opens the Hotkeys keyboard key selection window.
  Sethotkeyfunctions1to48         = 293, // to 343	Opens a Function selection window for the hotkeys.
  Setinputtriggerfunctions1to48   = 344, // to 394	Opens a Function selection window for the input triggers.
  SelectTABlayer                  = 400, // to 449	Selects the TAB layer on the screen. The layer number selected is the function code - 400, so TAB layer 1. selected with code 401. Note: To select a sub layer with a hotkey or with an input trigger configure the same key or pin to select all of it's parent layers and also the layer itself, so the parent layers and the sub layers will also be selected and the sub layer will always showup this way, no matter which parent layer was originally shown.
  SetoutputtriggerLEDs1to48       = 450, // - 500	Opens a LED selection window for the output triggers.
  CAM_ImportDXF                   = 501, // Imports a dxf drawing file to UCCAM.
  CAM_Generatetoolpath            = 502, // Generates the toolpath in UCCAM.
  CAM_Generategcode               = 503, // Creates the gcode in UCCAM.
  M3on                            = 504, // Switches the M3 spindle CW button on.
  M3off                           = 505, // Switches the M3 spindle CW button off.
  M4on                            = 506, // Switches the M4 spindle CCW button on.
  M4off                           = 507, // Switches the M4 spindle CCW button off.
  M7on                            = 508, // Switches the M7 mist button on.
  M7off                           = 509, // Switches the M7 mist button off.
  M8on                            = 510, // Switches the M8 flood button on.
  M8off                           = 511, // Switches the M8 flood button off.
  Reseton                         = 512, // Switches the Reset button on.
  Resetoff                        = 513, // Switches the Reset button off.
  Offlineon                       = 514, // Switches the Offline button on.
  Offlineoff                      = 515, // Switches the Offline button off.
  Machinecoordson                 = 516, // Switches the machine coordinates button on.
  Machinecoordsoff                = 517, // Switches the machine coordinates button off.
  Softlimitson                    = 518, // Switches the softlimits setting on.
  Softlimitsoff                   = 519, // Switches the softlimits setting off.
  THCon                           = 520, // Switches the THC control on.
  THCoff                          = 521, // Switches the THC control off.
  Feedholdtoggle                  = 522, // Toggles the feedhold button.
  Feedholdon                      = 523, // Switches the feedhold button on.
  Feedholdoff                     = 524, // Switches the feedhold button off.
  Configplugins                   = 525, // Opens the plugin configuration window
  Editscreen                      = 526, // Enters the screen editor mode
  Savealloffsets                  = 527, // Saves all offset values to the profile file.
  Clearstatusmessages             = 528, // Clears the Status message box
  THCAntiDiveon                   = 529, // Switches the Anti Dive function for the THC on.
  THCAntiDiveoff                  = 530, // Switches the Anti Dive function for the THC off.
  THCAntiDivetoggle               = 531, // Toggles the Anti Dive function for the THC.
  Configmacroloops                = 532, // Opens the macroloop configuration window.
  THCDelayon                      = 533, // Switches the THC Delay function for the THC on.
  THCDelayoff                     = 534, // Switches the THC Delay function for the THC off.
  THCDelaytoggle                  = 535, // Toggles the Delay function for the THC.
  THCarconsignalon_emulation      = 536, // Switches the THC arcon virtual signal on. Can be used to emulate the THC arcon signal from keyboard.
  THCarconsignaloff_emulation     = 537, // Switches the THC arcon virtual signal off. Can be used to emulate the THC arcon signal from keyboard.
  THCupsignalon_emulation         = 538, // Switches the THC up virtual signal on. Can be used to emulate the THC up signal from keyboard.
  THCupsignaloff_emulation        = 539, // Switches the THC up virtual signal off. Can be used to emulate the THC up signal from keyboard.
  THCdownsignalon_emulation       = 540, // Switches the THC down virtual signal on. Can be used to emulate the THC down signal from keyboard.
  THCdownsignaloff_emulation      = 541, // Switches the THC down virtual signal off. Can be used to emulate the THC down signal from keyboard.
  THCAntiDownon                   = 542, // Switches the Anti Down function for the THC on.
  THCAntiDownoff                  = 543, // Switches the Anti Down function for the THC off.
  THCAntiDowntoggle               = 544, // Toggles the Anti Down function for the THC.
  Safeprobemodeon                 = 545, // Switches the safe probe mode on.
  Safeprobemodeoff                = 546, // Switches the safe probe mode off.
  Safeprobemodetoggle             = 547, // Toggles the safe probe mode.
  Operatorlock                    = 548, // Opens the operator lock/unlock window.
  Showstatistics                  = 549, // Opens the machine statistics window.
  ShowSpindlepulleys              = 550, // Opens the Spindle pulleys selection window.
  Digitize_setfilename            = 551, // Sets the file name to save the Digitized points to.
  JogSafeprobemodeon              = 552, // Switches the jog safe probe mode on.
  JogSafeprobemodeoff             = 553, // Switches the jog safe probe mode off.
  JogSafeprobemodetoggle          = 554, // Toggles the jog safe probe mode.
  ReloadGcodefile                 = 555, // Reloads the g-code file if a file is already loaded.
  JograteResetto100percent        = 556, // Resets the jog rate field to 100%.
  FROResetto100percent            = 557, // Resets the feed override to 100%.
  SROResetto100percent            = 558, // Resets the spindle speed override to 100%.
  M1optionalstopon                = 559, // Switches the M1 optional stop on.
  M1optionalstopoff               = 560, // Switches the M1 optional stop off.
  M1optionalstoptoggle            = 561, // Toggles the M1 optional stop state.
  Sethotkeycodes49to96            = 562, // to 612	Opens the Hotkeys keyboard key selection window.
  Sethotkeyfunctions49to96        = 613, // to 663	Opens a Function selection window for the hotkeys.
  Setinputtriggerfunctions49to96  = 664, // to 714	Opens a Function selection window for the input triggers.
  SetoutputtriggerLEDs49to96      = 715, // - 762	Opens a LED selection window for the output triggers.
  // R*	(reserved)
  JogpanelShow                    = 770, // Shows the jog panel.
  JogpanelHide                    = 771, // Hides the jog panel.
  JogpanelToggle                  = 772, // Toggles the jog panel visibility state.
  OpenSpindlePIDsetup             = 773, // Opens the Spindle PID controller setup window.
  // 774-999 R*	(reserved)

};

#endif // _TYPES_H
